// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: seckill.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreSeckillCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	StockQuantity int64                  `protobuf:"varint,3,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	SeckillPrice  string                 `protobuf:"bytes,4,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxPerLimit   int64                  `protobuf:"varint,7,opt,name=max_per_limit,json=maxPerLimit,proto3" json:"max_per_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSeckillCreateReq) Reset() {
	*x = PreSeckillCreateReq{}
	mi := &file_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSeckillCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSeckillCreateReq) ProtoMessage() {}

func (x *PreSeckillCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSeckillCreateReq.ProtoReflect.Descriptor instead.
func (*PreSeckillCreateReq) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *PreSeckillCreateReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *PreSeckillCreateReq) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *PreSeckillCreateReq) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *PreSeckillCreateReq) GetSeckillPrice() string {
	if x != nil {
		return x.SeckillPrice
	}
	return ""
}

func (x *PreSeckillCreateReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PreSeckillCreateReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *PreSeckillCreateReq) GetMaxPerLimit() int64 {
	if x != nil {
		return x.MaxPerLimit
	}
	return 0
}

type PreSeckillCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info          string                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSeckillCreateResp) Reset() {
	*x = PreSeckillCreateResp{}
	mi := &file_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSeckillCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSeckillCreateResp) ProtoMessage() {}

func (x *PreSeckillCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSeckillCreateResp.ProtoReflect.Descriptor instead.
func (*PreSeckillCreateResp) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *PreSeckillCreateResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PreSeckillCreateResp) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type SearchStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStockReq) Reset() {
	*x = SearchStockReq{}
	mi := &file_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStockReq) ProtoMessage() {}

func (x *SearchStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStockReq.ProtoReflect.Descriptor instead.
func (*SearchStockReq) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *SearchStockReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type SearchStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         int64                  `protobuf:"varint,1,opt,name=stock,proto3" json:"stock,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStockResp) Reset() {
	*x = SearchStockResp{}
	mi := &file_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStockResp) ProtoMessage() {}

func (x *SearchStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStockResp.ProtoReflect.Descriptor instead.
func (*SearchStockResp) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *SearchStockResp) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SearchStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchStockResp) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type SeckillOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillOrderReq) Reset() {
	*x = SeckillOrderReq{}
	mi := &file_seckill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillOrderReq) ProtoMessage() {}

func (x *SeckillOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillOrderReq.ProtoReflect.Descriptor instead.
func (*SeckillOrderReq) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *SeckillOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillOrderReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillOrderReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SeckillOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info          string                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillOrderResp) Reset() {
	*x = SeckillOrderResp{}
	mi := &file_seckill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillOrderResp) ProtoMessage() {}

func (x *SeckillOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillOrderResp.ProtoReflect.Descriptor instead.
func (*SeckillOrderResp) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *SeckillOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeckillOrderResp) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_seckill_proto protoreflect.FileDescriptor

const file_seckill_proto_rawDesc = "" +
	"\n" +
	"\rseckill.proto\x12\aseckill\"\x81\x02\n" +
	"\x13PreSeckillCreateReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12%\n" +
	"\x0estock_quantity\x18\x03 \x01(\x03R\rstockQuantity\x12#\n" +
	"\rseckill_price\x18\x04 \x01(\tR\fseckillPrice\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\"\n" +
	"\rmax_per_limit\x18\a \x01(\x03R\vmaxPerLimit\"D\n" +
	"\x14PreSeckillCreateResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04info\x18\x02 \x01(\tR\x04info\"/\n" +
	"\x0eSearchStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"U\n" +
	"\x0fSearchStockResp\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\x03R\x05stock\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\"e\n" +
	"\x0fSeckillOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"@\n" +
	"\x10SeckillOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04info\x18\x02 \x01(\tR\x04info2\xe7\x01\n" +
	"\rSeckillServer\x12O\n" +
	"\x10PreSeckillCreate\x12\x1c.seckill.PreSeckillCreateReq\x1a\x1d.seckill.PreSeckillCreateResp\x12@\n" +
	"\vSearchStock\x12\x17.seckill.SearchStockReq\x1a\x18.seckill.SearchStockResp\x12C\n" +
	"\fSeckillOrder\x12\x18.seckill.SeckillOrderReq\x1a\x19.seckill.SeckillOrderRespB\x03Z\x01.b\x06proto3"

var (
	file_seckill_proto_rawDescOnce sync.Once
	file_seckill_proto_rawDescData []byte
)

func file_seckill_proto_rawDescGZIP() []byte {
	file_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)))
	})
	return file_seckill_proto_rawDescData
}

var file_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_seckill_proto_goTypes = []any{
	(*PreSeckillCreateReq)(nil),  // 0: seckill.PreSeckillCreateReq
	(*PreSeckillCreateResp)(nil), // 1: seckill.PreSeckillCreateResp
	(*SearchStockReq)(nil),       // 2: seckill.SearchStockReq
	(*SearchStockResp)(nil),      // 3: seckill.SearchStockResp
	(*SeckillOrderReq)(nil),      // 4: seckill.SeckillOrderReq
	(*SeckillOrderResp)(nil),     // 5: seckill.SeckillOrderResp
}
var file_seckill_proto_depIdxs = []int32{
	0, // 0: seckill.SeckillServer.PreSeckillCreate:input_type -> seckill.PreSeckillCreateReq
	2, // 1: seckill.SeckillServer.SearchStock:input_type -> seckill.SearchStockReq
	4, // 2: seckill.SeckillServer.SeckillOrder:input_type -> seckill.SeckillOrderReq
	1, // 3: seckill.SeckillServer.PreSeckillCreate:output_type -> seckill.PreSeckillCreateResp
	3, // 4: seckill.SeckillServer.SearchStock:output_type -> seckill.SearchStockResp
	5, // 5: seckill.SeckillServer.SeckillOrder:output_type -> seckill.SeckillOrderResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seckill_proto_init() }
func file_seckill_proto_init() {
	if File_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_proto_msgTypes,
	}.Build()
	File_seckill_proto = out.File
	file_seckill_proto_goTypes = nil
	file_seckill_proto_depIdxs = nil
}
