// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: seckill.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeckillServer_PreSeckillCreate_FullMethodName = "/seckill.SeckillServer/PreSeckillCreate"
	SeckillServer_SearchStock_FullMethodName      = "/seckill.SeckillServer/SearchStock"
	SeckillServer_SeckillOrder_FullMethodName     = "/seckill.SeckillServer/SeckillOrder"
)

// SeckillServerClient is the client API for SeckillServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeckillServerClient interface {
	PreSeckillCreate(ctx context.Context, in *PreSeckillCreateReq, opts ...grpc.CallOption) (*PreSeckillCreateResp, error)
	SearchStock(ctx context.Context, in *SearchStockReq, opts ...grpc.CallOption) (*SearchStockResp, error)
	SeckillOrder(ctx context.Context, in *SeckillOrderReq, opts ...grpc.CallOption) (*SeckillOrderResp, error)
}

type seckillServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillServerClient(cc grpc.ClientConnInterface) SeckillServerClient {
	return &seckillServerClient{cc}
}

func (c *seckillServerClient) PreSeckillCreate(ctx context.Context, in *PreSeckillCreateReq, opts ...grpc.CallOption) (*PreSeckillCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreSeckillCreateResp)
	err := c.cc.Invoke(ctx, SeckillServer_PreSeckillCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServerClient) SearchStock(ctx context.Context, in *SearchStockReq, opts ...grpc.CallOption) (*SearchStockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchStockResp)
	err := c.cc.Invoke(ctx, SeckillServer_SearchStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServerClient) SeckillOrder(ctx context.Context, in *SeckillOrderReq, opts ...grpc.CallOption) (*SeckillOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillOrderResp)
	err := c.cc.Invoke(ctx, SeckillServer_SeckillOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillServerServer is the server API for SeckillServer service.
// All implementations must embed UnimplementedSeckillServerServer
// for forward compatibility.
type SeckillServerServer interface {
	PreSeckillCreate(context.Context, *PreSeckillCreateReq) (*PreSeckillCreateResp, error)
	SearchStock(context.Context, *SearchStockReq) (*SearchStockResp, error)
	SeckillOrder(context.Context, *SeckillOrderReq) (*SeckillOrderResp, error)
	mustEmbedUnimplementedSeckillServerServer()
}

// UnimplementedSeckillServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeckillServerServer struct{}

func (UnimplementedSeckillServerServer) PreSeckillCreate(context.Context, *PreSeckillCreateReq) (*PreSeckillCreateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PreSeckillCreate not implemented")
}
func (UnimplementedSeckillServerServer) SearchStock(context.Context, *SearchStockReq) (*SearchStockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchStock not implemented")
}
func (UnimplementedSeckillServerServer) SeckillOrder(context.Context, *SeckillOrderReq) (*SeckillOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SeckillOrder not implemented")
}
func (UnimplementedSeckillServerServer) mustEmbedUnimplementedSeckillServerServer() {}
func (UnimplementedSeckillServerServer) testEmbeddedByValue()                       {}

// UnsafeSeckillServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeckillServerServer will
// result in compilation errors.
type UnsafeSeckillServerServer interface {
	mustEmbedUnimplementedSeckillServerServer()
}

func RegisterSeckillServerServer(s grpc.ServiceRegistrar, srv SeckillServerServer) {
	// If the following call panics, it indicates UnimplementedSeckillServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeckillServer_ServiceDesc, srv)
}

func _SeckillServer_PreSeckillCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreSeckillCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServerServer).PreSeckillCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillServer_PreSeckillCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServerServer).PreSeckillCreate(ctx, req.(*PreSeckillCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillServer_SearchStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServerServer).SearchStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillServer_SearchStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServerServer).SearchStock(ctx, req.(*SearchStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillServer_SeckillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServerServer).SeckillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillServer_SeckillOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServerServer).SeckillOrder(ctx, req.(*SeckillOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SeckillServer_ServiceDesc is the grpc.ServiceDesc for SeckillServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeckillServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.SeckillServer",
	HandlerType: (*SeckillServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreSeckillCreate",
			Handler:    _SeckillServer_PreSeckillCreate_Handler,
		},
		{
			MethodName: "SearchStock",
			Handler:    _SeckillServer_SearchStock_Handler,
		},
		{
			MethodName: "SeckillOrder",
			Handler:    _SeckillServer_SeckillOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seckill.proto",
}
